//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo3D.Components.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Demo3D.Components.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actuation Controller.
        /// </summary>
        public static string ActuationController {
            get {
                return ResourceManager.GetString("ActuationController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        public static string ActuationController_Activate {
            get {
                return ResourceManager.GetString("ActuationController_Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True to travel towards the upper limit, false to travel towards the lower limit..
        /// </summary>
        public static string ActuationController_Activate_Description {
            get {
                return ResourceManager.GetString("ActuationController_Activate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A motor controller that exposes a single &quot;activate&quot; input for travelling back and forth between limits..
        /// </summary>
        public static string ActuationController_Description {
            get {
                return ResourceManager.GetString("ActuationController_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motor.
        /// </summary>
        public static string ActuationController_Motor {
            get {
                return ResourceManager.GetString("ActuationController_Motor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The motor that the controller is currently bound to..
        /// </summary>
        public static string ActuationController_Motor_Description {
            get {
                return ResourceManager.GetString("ActuationController_Motor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ActuationController_Name {
            get {
                return ResourceManager.GetString("ActuationController_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name for the controller..
        /// </summary>
        public static string ActuationController_Name_Description {
            get {
                return ResourceManager.GetString("ActuationController_Name_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angular Motor.
        /// </summary>
        public static string AngularMotor {
            get {
                return ResourceManager.GetString("AngularMotor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The acceleration for the angular motor (zero for infinite acceleration)..
        /// </summary>
        public static string AngularMotor_Acceleration_Description {
            get {
                return ResourceManager.GetString("AngularMotor_Acceleration_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current angle..
        /// </summary>
        public static string AngularMotor_Angle_Description {
            get {
                return ResourceManager.GetString("AngularMotor_Angle_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether to feedback the angle of the motor..
        /// </summary>
        public static string AngularMotor_AngleFeedback_Description {
            get {
                return ResourceManager.GetString("AngularMotor_AngleFeedback_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The feedback resolution for the angle..
        /// </summary>
        public static string AngularMotor_AngleResolution_Description {
            get {
                return ResourceManager.GetString("AngularMotor_AngleResolution_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The control mode for the linear motor..
        /// </summary>
        public static string AngularMotor_ControlMode_Description {
            get {
                return ResourceManager.GetString("AngularMotor_ControlMode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The deceleration for the angular motor (zero for infinite deceleration)..
        /// </summary>
        public static string AngularMotor_Deceleration_Description {
            get {
                return ResourceManager.GetString("AngularMotor_Deceleration_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current direction for the angular motor..
        /// </summary>
        public static string AngularMotor_Direction_Description {
            get {
                return ResourceManager.GetString("AngularMotor_Direction_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The initial angle..
        /// </summary>
        public static string AngularMotor_InitialAngle_Description {
            get {
                return ResourceManager.GetString("AngularMotor_InitialAngle_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The initial (on initialize) state for the angular motor..
        /// </summary>
        public static string AngularMotor_InitialState_Description {
            get {
                return ResourceManager.GetString("AngularMotor_InitialState_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target speed for the angular motor..
        /// </summary>
        public static string AngularMotor_Speed_Description {
            get {
                return ResourceManager.GetString("AngularMotor_Speed_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current state for the angular motor..
        /// </summary>
        public static string AngularMotor_State_Description {
            get {
                return ResourceManager.GetString("AngularMotor_State_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target angle to drive towards..
        /// </summary>
        public static string AngularMotor_Target_Description {
            get {
                return ResourceManager.GetString("AngularMotor_Target_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the angular motor should be automatically driven towards a target distance..
        /// </summary>
        public static string AngularMotor_TargetEnabled_Description {
            get {
                return ResourceManager.GetString("AngularMotor_TargetEnabled_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Panels.
        /// </summary>
        public static string ControlPanels_Category {
            get {
                return ResourceManager.GetString("ControlPanels_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostic Sensor.
        /// </summary>
        public static string DiagnosticSensor {
            get {
                return ResourceManager.GetString("DiagnosticSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list of visuals currently blocking the diagnostic sensor..
        /// </summary>
        public static string DiagnosticSensor_BlockingVisuals_Description {
            get {
                return ResourceManager.GetString("DiagnosticSensor_BlockingVisuals_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The labels/tags for visuals that should be detected by the diagnostic sensor (use &quot;*&quot; to detect all)..
        /// </summary>
        public static string DiagnosticSensor_Detect_Description {
            get {
                return ResourceManager.GetString("DiagnosticSensor_Detect_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether to highlight all visuals blocking the diagnostic sensor..
        /// </summary>
        public static string DiagnosticSensor_HighlightBlockingVisuals_Description {
            get {
                return ResourceManager.GetString("DiagnosticSensor_HighlightBlockingVisuals_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the diagnostic sensor is currently blocked..
        /// </summary>
        public static string DiagnosticSensor_IsBlocked_Description {
            get {
                return ResourceManager.GetString("DiagnosticSensor_IsBlocked_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The labels/tags to mark this visual with..
        /// </summary>
        public static string DiagnosticSensor_Labels_Description {
            get {
                return ResourceManager.GetString("DiagnosticSensor_Labels_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string DiagnosticSensor_Name {
            get {
                return ResourceManager.GetString("DiagnosticSensor_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether to stop the model when the diagnostic sensor is blocked..
        /// </summary>
        public static string DiagnosticSensor_StopOnBlocked_Description {
            get {
                return ResourceManager.GetString("DiagnosticSensor_StopOnBlocked_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance Load Source.
        /// </summary>
        public static string DistanceLoadSource {
            get {
                return ResourceManager.GetString("DistanceLoadSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The conveyor aspect..
        /// </summary>
        public static string DistanceLoadSource_Conveyor_Description {
            get {
                return ResourceManager.GetString("DistanceLoadSource_Conveyor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The conveyor distance to travel between consecutive loads..
        /// </summary>
        public static string DistanceLoadSource_Distance_Description {
            get {
                return ResourceManager.GetString("DistanceLoadSource_Distance_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the loads should be created with the velocity of the conveyor surface..
        /// </summary>
        public static string DistanceLoadSource_InitialConveyorVelocity_Description {
            get {
                return ResourceManager.GetString("DistanceLoadSource_InitialConveyorVelocity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance Sensor.
        /// </summary>
        public static string DistanceSensor {
            get {
                return ResourceManager.GetString("DistanceSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The (local) location for the distance sensor..
        /// </summary>
        public static string DistanceSensor_Anchor_Description {
            get {
                return ResourceManager.GetString("DistanceSensor_Anchor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The (local) direction for the detector beam..
        /// </summary>
        public static string DistanceSensor_Axis_Description {
            get {
                return ResourceManager.GetString("DistanceSensor_Axis_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The control mode for the distance sensor..
        /// </summary>
        public static string DistanceSensor_ControlMode_Description {
            get {
                return ResourceManager.GetString("DistanceSensor_ControlMode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The diameter for the detector beam at the distance sensor&apos;s maximum range..
        /// </summary>
        public static string DistanceSensor_Diameter_Description {
            get {
                return ResourceManager.GetString("DistanceSensor_Diameter_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The distance of the blocking load (negative if not blocked)..
        /// </summary>
        public static string DistanceSensor_Distance_Description {
            get {
                return ResourceManager.GetString("DistanceSensor_Distance_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the distance sensor is currently blocked..
        /// </summary>
        public static string DistanceSensor_IsBlocked_Description {
            get {
                return ResourceManager.GetString("DistanceSensor_IsBlocked_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string DistanceSensor_Name {
            get {
                return ResourceManager.GetString("DistanceSensor_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum range for the detector beam..
        /// </summary>
        public static string DistanceSensor_Range_Description {
            get {
                return ResourceManager.GetString("DistanceSensor_Range_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of times per second that a distance will be calculated..
        /// </summary>
        public static string DistanceSensor_SampleRate_Description {
            get {
                return ResourceManager.GetString("DistanceSensor_SampleRate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Separation.
        /// </summary>
        public static string DistanceSensor_ScanSeparation {
            get {
                return ResourceManager.GetString("DistanceSensor_ScanSeparation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The distance between scan rays..
        /// </summary>
        public static string DistanceSensor_ScanSeparation_Description {
            get {
                return ResourceManager.GetString("DistanceSensor_ScanSeparation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The color to compare against..
        /// </summary>
        public static string DistanceSensor_TargetColor_Description {
            get {
                return ResourceManager.GetString("DistanceSensor_TargetColor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The euclidean distance of the blocking load&apos;s color from the target color (negative if not blocked)..
        /// </summary>
        public static string DistanceSensor_TargetColorDistance_Description {
            get {
                return ResourceManager.GetString("DistanceSensor_TargetColorDistance_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Effectors.
        /// </summary>
        public static string EndEffectors_Category {
            get {
                return ResourceManager.GetString("EndEffectors_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic Controller.
        /// </summary>
        public static string GenericController {
            get {
                return ResourceManager.GetString("GenericController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceleration.
        /// </summary>
        public static string GenericController_Acceleration {
            get {
                return ResourceManager.GetString("GenericController_Acceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum acceleration for the motor (zero for infinite)..
        /// </summary>
        public static string GenericController_Acceleration_Description {
            get {
                return ResourceManager.GetString("GenericController_Acceleration_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deceleration.
        /// </summary>
        public static string GenericController_Deceleration {
            get {
                return ResourceManager.GetString("GenericController_Deceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum deceleration for the motor (zero for infinite)..
        /// </summary>
        public static string GenericController_Deceleration_Description {
            get {
                return ResourceManager.GetString("GenericController_Deceleration_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forwards.
        /// </summary>
        public static string GenericController_Forwards {
            get {
                return ResourceManager.GetString("GenericController_Forwards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the desired direction of travel for the motor is forwards..
        /// </summary>
        public static string GenericController_Forwards_Description {
            get {
                return ResourceManager.GetString("GenericController_Forwards_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inputs.
        /// </summary>
        public static string GenericController_Inputs {
            get {
                return ResourceManager.GetString("GenericController_Inputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies which inputs that the controller should expose..
        /// </summary>
        public static string GenericController_Inputs_Description {
            get {
                return ResourceManager.GetString("GenericController_Inputs_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motor.
        /// </summary>
        public static string GenericController_Motor {
            get {
                return ResourceManager.GetString("GenericController_Motor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The motor that the controller is currently bound to..
        /// </summary>
        public static string GenericController_Motor_Description {
            get {
                return ResourceManager.GetString("GenericController_Motor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string GenericController_Name {
            get {
                return ResourceManager.GetString("GenericController_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name for the controller..
        /// </summary>
        public static string GenericController_Name_Description {
            get {
                return ResourceManager.GetString("GenericController_Name_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse.
        /// </summary>
        public static string GenericController_Reverse {
            get {
                return ResourceManager.GetString("GenericController_Reverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the desired direction of travel for the motor is backwards..
        /// </summary>
        public static string GenericController_Reverse_Description {
            get {
                return ResourceManager.GetString("GenericController_Reverse_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        public static string GenericController_Speed {
            get {
                return ResourceManager.GetString("GenericController_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The desired (unsigned) speed for the motor..
        /// </summary>
        public static string GenericController_Speed_Description {
            get {
                return ResourceManager.GetString("GenericController_Speed_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string GenericController_State {
            get {
                return ResourceManager.GetString("GenericController_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The desired state for the motor..
        /// </summary>
        public static string GenericController_State_Description {
            get {
                return ResourceManager.GetString("GenericController_State_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicator Light.
        /// </summary>
        public static string IndicatorLight {
            get {
                return ResourceManager.GetString("IndicatorLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Stack.
        /// </summary>
        public static string LightStack {
            get {
                return ResourceManager.GetString("LightStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit Sensor.
        /// </summary>
        public static string LimitSensor {
            get {
                return ResourceManager.GetString("LimitSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At Lower Limit.
        /// </summary>
        public static string LimitSensor_AtLowerLimit {
            get {
                return ResourceManager.GetString("LimitSensor_AtLowerLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the lower limit has been reached or exceeded according to the specified tolerance..
        /// </summary>
        public static string LimitSensor_AtLowerLimit_Description {
            get {
                return ResourceManager.GetString("LimitSensor_AtLowerLimit_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At Upper Limit.
        /// </summary>
        public static string LimitSensor_AtUpperLimit {
            get {
                return ResourceManager.GetString("LimitSensor_AtUpperLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the upper limit has been reached or exceeded according to the specified tolerance..
        /// </summary>
        public static string LimitSensor_AtUpperLimit_Description {
            get {
                return ResourceManager.GetString("LimitSensor_AtUpperLimit_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency.
        /// </summary>
        public static string LimitSensor_Frequency {
            get {
                return ResourceManager.GetString("LimitSensor_Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of times that the outputs should be updated per second..
        /// </summary>
        public static string LimitSensor_Frequency_Description {
            get {
                return ResourceManager.GetString("LimitSensor_Frequency_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lower Limit.
        /// </summary>
        public static string LimitSensor_LowerLimit {
            get {
                return ResourceManager.GetString("LimitSensor_LowerLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lower limit..
        /// </summary>
        public static string LimitSensor_LowerLimit_Description {
            get {
                return ResourceManager.GetString("LimitSensor_LowerLimit_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motor.
        /// </summary>
        public static string LimitSensor_Motor {
            get {
                return ResourceManager.GetString("LimitSensor_Motor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The motor that the limit sensor is currently bound to..
        /// </summary>
        public static string LimitSensor_Motor_Description {
            get {
                return ResourceManager.GetString("LimitSensor_Motor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outputs.
        /// </summary>
        public static string LimitSensor_Outputs {
            get {
                return ResourceManager.GetString("LimitSensor_Outputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies which outputs the sensor should expose..
        /// </summary>
        public static string LimitSensor_Outputs_Description {
            get {
                return ResourceManager.GetString("LimitSensor_Outputs_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tolerance.
        /// </summary>
        public static string LimitSensor_Tolerance {
            get {
                return ResourceManager.GetString("LimitSensor_Tolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tolerance to use when determining whether the motor has reached or exceeded a limit..
        /// </summary>
        public static string LimitSensor_Tolerance_Description {
            get {
                return ResourceManager.GetString("LimitSensor_Tolerance_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upper Limit.
        /// </summary>
        public static string LimitSensor_UpperLimit {
            get {
                return ResourceManager.GetString("LimitSensor_UpperLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The upper limit..
        /// </summary>
        public static string LimitSensor_UpperLimit_Description {
            get {
                return ResourceManager.GetString("LimitSensor_UpperLimit_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Motor Limits.
        /// </summary>
        public static string LimitSensor_UseMotorLimits {
            get {
                return ResourceManager.GetString("LimitSensor_UseMotorLimits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether to use the limits on the motor to which the limit sensor is bound..
        /// </summary>
        public static string LimitSensor_UseMotorLimits_Description {
            get {
                return ResourceManager.GetString("LimitSensor_UseMotorLimits_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit Switch.
        /// </summary>
        public static string LimitSwitch {
            get {
                return ResourceManager.GetString("LimitSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the motor is currently at (or exceeding) the lower limit..
        /// </summary>
        public static string LimitSwitch_AtLowerLimit_Description {
            get {
                return ResourceManager.GetString("LimitSwitch_AtLowerLimit_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the motor is currently at (or exceeding) the upper limit..
        /// </summary>
        public static string LimitSwitch_AtUpperLimit_Description {
            get {
                return ResourceManager.GetString("LimitSwitch_AtUpperLimit_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The control mode for the limit switch..
        /// </summary>
        public static string LimitSwitch_ControlMode_Description {
            get {
                return ResourceManager.GetString("LimitSwitch_ControlMode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lower limit for the limit switch..
        /// </summary>
        public static string LimitSwitch_LowerLimit_Description {
            get {
                return ResourceManager.GetString("LimitSwitch_LowerLimit_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the limit switch observes a lower limit..
        /// </summary>
        public static string LimitSwitch_LowerLimitEnabled_Description {
            get {
                return ResourceManager.GetString("LimitSwitch_LowerLimitEnabled_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The motor controlled by the limit switch..
        /// </summary>
        public static string LimitSwitch_Motor_Description {
            get {
                return ResourceManager.GetString("LimitSwitch_Motor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether to switch off the motor at the lower limit..
        /// </summary>
        public static string LimitSwitch_SwitchAtLowerLimit_Description {
            get {
                return ResourceManager.GetString("LimitSwitch_SwitchAtLowerLimit_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether to switch off the motor at the upper limit..
        /// </summary>
        public static string LimitSwitch_SwitchAtUpperLimit_Description {
            get {
                return ResourceManager.GetString("LimitSwitch_SwitchAtUpperLimit_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The upper limit for the limit switch..
        /// </summary>
        public static string LimitSwitch_UpperLimit_Description {
            get {
                return ResourceManager.GetString("LimitSwitch_UpperLimit_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the limit switch observes an upper limit..
        /// </summary>
        public static string LimitSwitch_UpperLimitEnabled_Description {
            get {
                return ResourceManager.GetString("LimitSwitch_UpperLimitEnabled_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linear Motor.
        /// </summary>
        public static string LinearMotor {
            get {
                return ResourceManager.GetString("LinearMotor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The acceleration for the linear motor (zero for infinite acceleration)..
        /// </summary>
        public static string LinearMotor_Acceleration_Description {
            get {
                return ResourceManager.GetString("LinearMotor_Acceleration_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The control mode for the linear motor..
        /// </summary>
        public static string LinearMotor_ControlMode_Description {
            get {
                return ResourceManager.GetString("LinearMotor_ControlMode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The deceleration for the linear motor (zero for infinite deceleration)..
        /// </summary>
        public static string LinearMotor_Deceleration_Description {
            get {
                return ResourceManager.GetString("LinearMotor_Deceleration_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current direction for the linear motor..
        /// </summary>
        public static string LinearMotor_Direction_Description {
            get {
                return ResourceManager.GetString("LinearMotor_Direction_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The initial distance..
        /// </summary>
        public static string LinearMotor_InitialPosition_Description {
            get {
                return ResourceManager.GetString("LinearMotor_InitialPosition_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The initial (on initialize) state for the linear motor..
        /// </summary>
        public static string LinearMotor_InitialState_Description {
            get {
                return ResourceManager.GetString("LinearMotor_InitialState_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current distance..
        /// </summary>
        public static string LinearMotor_Position_Description {
            get {
                return ResourceManager.GetString("LinearMotor_Position_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether to feedback the position of the motor..
        /// </summary>
        public static string LinearMotor_PositionFeedback_Description {
            get {
                return ResourceManager.GetString("LinearMotor_PositionFeedback_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The feedback resolution for the position..
        /// </summary>
        public static string LinearMotor_PositionResolution_Description {
            get {
                return ResourceManager.GetString("LinearMotor_PositionResolution_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target speed for the linear motor..
        /// </summary>
        public static string LinearMotor_Speed_Description {
            get {
                return ResourceManager.GetString("LinearMotor_Speed_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current state for the linear motor..
        /// </summary>
        public static string LinearMotor_State_Description {
            get {
                return ResourceManager.GetString("LinearMotor_State_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target distance to drive towards..
        /// </summary>
        public static string LinearMotor_Target_Description {
            get {
                return ResourceManager.GetString("LinearMotor_Target_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the linear motor should be automatically driven towards a target distance..
        /// </summary>
        public static string LinearMotor_TargetEnabled_Description {
            get {
                return ResourceManager.GetString("LinearMotor_TargetEnabled_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum distance at which loads can be attached to the fixture..
        /// </summary>
        public static string LoadFixture_AttachmentRadius_Description {
            get {
                return ResourceManager.GetString("LoadFixture_AttachmentRadius_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list of types for filtering which loads can be attached to the fixture, separated by comma..
        /// </summary>
        public static string LoadFixture_FilterTypes_Description {
            get {
                return ResourceManager.GetString("LoadFixture_FilterTypes_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The relative position offset to use when recentering..
        /// </summary>
        public static string LoadFixture_PositionOffset_Description {
            get {
                return ResourceManager.GetString("LoadFixture_PositionOffset_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether to recenter loads when attaching to the fixture..
        /// </summary>
        public static string LoadFixture_Recenter_Description {
            get {
                return ResourceManager.GetString("LoadFixture_Recenter_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The relative rotation offset to use when recentering..
        /// </summary>
        public static string LoadFixture_RotationOffset_Description {
            get {
                return ResourceManager.GetString("LoadFixture_RotationOffset_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loads.
        /// </summary>
        public static string Loads_Category {
            get {
                return ResourceManager.GetString("Loads_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Sink.
        /// </summary>
        public static string LoadSink {
            get {
                return ResourceManager.GetString("LoadSink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congestion Zone.
        /// </summary>
        public static string LoadSource_CongestionZone {
            get {
                return ResourceManager.GetString("LoadSource_CongestionZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the congestion zone must be cleared before a load is released..
        /// </summary>
        public static string LoadSource_CongestionZone_Description {
            get {
                return ResourceManager.GetString("LoadSource_CongestionZone_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string LoadSource_Name {
            get {
                return ResourceManager.GetString("LoadSource_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mechanical Gripper.
        /// </summary>
        public static string MechanicalGripper {
            get {
                return ResourceManager.GetString("MechanicalGripper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motion Sensor.
        /// </summary>
        public static string MotionSensor {
            get {
                return ResourceManager.GetString("MotionSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceleration.
        /// </summary>
        public static string MotionSensor_Acceleration {
            get {
                return ResourceManager.GetString("MotionSensor_Acceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The most recently recorded acceleration..
        /// </summary>
        public static string MotionSensor_Acceleration_Description {
            get {
                return ResourceManager.GetString("MotionSensor_Acceleration_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anchor.
        /// </summary>
        public static string MotionSensor_Anchor {
            get {
                return ResourceManager.GetString("MotionSensor_Anchor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The point on a visual to which the sensor is attached..
        /// </summary>
        public static string MotionSensor_Anchor_Description {
            get {
                return ResourceManager.GetString("MotionSensor_Anchor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axis.
        /// </summary>
        public static string MotionSensor_Axis {
            get {
                return ResourceManager.GetString("MotionSensor_Axis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The (optional) axis for which the position, velocity and acceleration is measured. If left empty then the position is the distance from the initial location and the velocity is the speed..
        /// </summary>
        public static string MotionSensor_Axis_Description {
            get {
                return ResourceManager.GetString("MotionSensor_Axis_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A sensor that reports the position, velocity and/or acceleration experienced by a point..
        /// </summary>
        public static string MotionSensor_Description {
            get {
                return ResourceManager.GetString("MotionSensor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency.
        /// </summary>
        public static string MotionSensor_Frequency {
            get {
                return ResourceManager.GetString("MotionSensor_Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The frequency at which the position, velocity and acceleration are measured (0 - 100Hz)..
        /// </summary>
        public static string MotionSensor_Frequency_Description {
            get {
                return ResourceManager.GetString("MotionSensor_Frequency_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outputs.
        /// </summary>
        public static string MotionSensor_Outputs {
            get {
                return ResourceManager.GetString("MotionSensor_Outputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sensor outputs that should be exposed..
        /// </summary>
        public static string MotionSensor_Outputs_Description {
            get {
                return ResourceManager.GetString("MotionSensor_Outputs_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string MotionSensor_Position {
            get {
                return ResourceManager.GetString("MotionSensor_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The most recently recorded position..
        /// </summary>
        public static string MotionSensor_Position_Description {
            get {
                return ResourceManager.GetString("MotionSensor_Position_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velocity.
        /// </summary>
        public static string MotionSensor_Velocity {
            get {
                return ResourceManager.GetString("MotionSensor_Velocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The most recently recorded velocity..
        /// </summary>
        public static string MotionSensor_Velocity_Description {
            get {
                return ResourceManager.GetString("MotionSensor_Velocity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motor Controllers.
        /// </summary>
        public static string Motor_Controllers_Category {
            get {
                return ResourceManager.GetString("Motor_Controllers_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motor Encoders.
        /// </summary>
        public static string Motor_Encoders_Category {
            get {
                return ResourceManager.GetString("Motor_Encoders_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motor Predictor.
        /// </summary>
        public static string MotorPredictor {
            get {
                return ResourceManager.GetString("MotorPredictor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string MotorPredictor_Name {
            get {
                return ResourceManager.GetString("MotorPredictor_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name for the motor predictor..
        /// </summary>
        public static string MotorPredictor_Name_Description {
            get {
                return ResourceManager.GetString("MotorPredictor_Name_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predicted Acceleration.
        /// </summary>
        public static string MotorPredictor_PredictedAcceleration {
            get {
                return ResourceManager.GetString("MotorPredictor_PredictedAcceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The most recent prediction made for the (signed) acceleration of the motor..
        /// </summary>
        public static string MotorPredictor_PredictedAcceleration_Description {
            get {
                return ResourceManager.GetString("MotorPredictor_PredictedAcceleration_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predicted Position.
        /// </summary>
        public static string MotorPredictor_PredictedPosition {
            get {
                return ResourceManager.GetString("MotorPredictor_PredictedPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The most recent prediction made for the position of the motor..
        /// </summary>
        public static string MotorPredictor_PredictedPosition_Description {
            get {
                return ResourceManager.GetString("MotorPredictor_PredictedPosition_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predicted Velocity.
        /// </summary>
        public static string MotorPredictor_PredictedVelocity {
            get {
                return ResourceManager.GetString("MotorPredictor_PredictedVelocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The most recent prediction made for the (signed) velocity of the motor..
        /// </summary>
        public static string MotorPredictor_PredictedVelocity_Description {
            get {
                return ResourceManager.GetString("MotorPredictor_PredictedVelocity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Position.
        /// </summary>
        public static string MotorPredictor_SourcePosition {
            get {
                return ResourceManager.GetString("MotorPredictor_SourcePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The most recent source position received..
        /// </summary>
        public static string MotorPredictor_SourcePosition_Description {
            get {
                return ResourceManager.GetString("MotorPredictor_SourcePosition_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout.
        /// </summary>
        public static string MotorPredictor_Timeout {
            get {
                return ResourceManager.GetString("MotorPredictor_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum time allowed between source position updates. No more predictions are made if this time is exceeded..
        /// </summary>
        public static string MotorPredictor_Timeout_Description {
            get {
                return ResourceManager.GetString("MotorPredictor_Timeout_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Step.
        /// </summary>
        public static string MotorPredictor_TimeStep {
            get {
                return ResourceManager.GetString("MotorPredictor_TimeStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The time-step for which predictions are made..
        /// </summary>
        public static string MotorPredictor_TimeStep_Description {
            get {
                return ResourceManager.GetString("MotorPredictor_TimeStep_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Type.
        /// </summary>
        public static string MotorPredictor_UnitType {
            get {
                return ResourceManager.GetString("MotorPredictor_UnitType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of units (linear or angular) for the motor..
        /// </summary>
        public static string MotorPredictor_UnitType_Description {
            get {
                return ResourceManager.GetString("MotorPredictor_UnitType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motors.
        /// </summary>
        public static string Motors_Category {
            get {
                return ResourceManager.GetString("Motors_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physics Geometry.
        /// </summary>
        public static string PhysicsGeometry_Category {
            get {
                return ResourceManager.GetString("PhysicsGeometry_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polling Encoder.
        /// </summary>
        public static string PollingEncoder {
            get {
                return ResourceManager.GetString("PollingEncoder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceleration.
        /// </summary>
        public static string PollingEncoder_Acceleration {
            get {
                return ResourceManager.GetString("PollingEncoder_Acceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The most recent encoding of the motor&apos;s acceleration..
        /// </summary>
        public static string PollingEncoder_Acceleration_Description {
            get {
                return ResourceManager.GetString("PollingEncoder_Acceleration_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A motor encoder that encodes the &quot;position&quot;, &quot;velocity&quot; and/or &quot;acceleration&quot; of the motor as outputs at fixed time intervals..
        /// </summary>
        public static string PollingEncoder_Description {
            get {
                return ResourceManager.GetString("PollingEncoder_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency.
        /// </summary>
        public static string PollingEncoder_Frequency {
            get {
                return ResourceManager.GetString("PollingEncoder_Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of times that the outputs should be updated per second..
        /// </summary>
        public static string PollingEncoder_Frequency_Description {
            get {
                return ResourceManager.GetString("PollingEncoder_Frequency_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motor.
        /// </summary>
        public static string PollingEncoder_Motor {
            get {
                return ResourceManager.GetString("PollingEncoder_Motor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The motor that the encoder is currently bound to..
        /// </summary>
        public static string PollingEncoder_Motor_Description {
            get {
                return ResourceManager.GetString("PollingEncoder_Motor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string PollingEncoder_Name {
            get {
                return ResourceManager.GetString("PollingEncoder_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name for the encoder..
        /// </summary>
        public static string PollingEncoder_Name_Description {
            get {
                return ResourceManager.GetString("PollingEncoder_Name_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outputs.
        /// </summary>
        public static string PollingEncoder_Outputs {
            get {
                return ResourceManager.GetString("PollingEncoder_Outputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies which outputs that the encoder should expose..
        /// </summary>
        public static string PollingEncoder_Outputs_Description {
            get {
                return ResourceManager.GetString("PollingEncoder_Outputs_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string PollingEncoder_Position {
            get {
                return ResourceManager.GetString("PollingEncoder_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The most recent encoding of the motor&apos;s position..
        /// </summary>
        public static string PollingEncoder_Position_Description {
            get {
                return ResourceManager.GetString("PollingEncoder_Position_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velocity.
        /// </summary>
        public static string PollingEncoder_Velocity {
            get {
                return ResourceManager.GetString("PollingEncoder_Velocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The most recent encoding of the motor&apos;s velocity..
        /// </summary>
        public static string PollingEncoder_Velocity_Description {
            get {
                return ResourceManager.GetString("PollingEncoder_Velocity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position Controller.
        /// </summary>
        public static string PositionController {
            get {
                return ResourceManager.GetString("PositionController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A motor controller that drives the motor towards a specified (signed) target position..
        /// </summary>
        public static string PositionController_Description {
            get {
                return ResourceManager.GetString("PositionController_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motor.
        /// </summary>
        public static string PositionController_Motor {
            get {
                return ResourceManager.GetString("PositionController_Motor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The motor that the controller is currently bound to..
        /// </summary>
        public static string PositionController_Motor_Description {
            get {
                return ResourceManager.GetString("PositionController_Motor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string PositionController_Name {
            get {
                return ResourceManager.GetString("PositionController_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name for the controller..
        /// </summary>
        public static string PositionController_Name_Description {
            get {
                return ResourceManager.GetString("PositionController_Name_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Mode.
        /// </summary>
        public static string PositionController_TargetMode {
            get {
                return ResourceManager.GetString("PositionController_TargetMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disontinuous mode (default) will follow the number line to the target. Continuous mode will take the shortest path to the target..
        /// </summary>
        public static string PositionController_TargetMode_Description {
            get {
                return ResourceManager.GetString("PositionController_TargetMode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Position.
        /// </summary>
        public static string PositionController_TargetPosition {
            get {
                return ResourceManager.GetString("PositionController_TargetPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The (signed) target position for the motor..
        /// </summary>
        public static string PositionController_TargetPosition_Description {
            get {
                return ResourceManager.GetString("PositionController_TargetPosition_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push Button.
        /// </summary>
        public static string PushButton {
            get {
                return ResourceManager.GetString("PushButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Load.
        /// </summary>
        public static string QuickLoad {
            get {
                return ResourceManager.GetString("QuickLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotary Switch.
        /// </summary>
        public static string RotarySwitch {
            get {
                return ResourceManager.GetString("RotarySwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensors.
        /// </summary>
        public static string Sensors_Category {
            get {
                return ResourceManager.GetString("Sensors_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Load Source.
        /// </summary>
        public static string ServerLoadSource {
            get {
                return ResourceManager.GetString("ServerLoadSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suction Gripper.
        /// </summary>
        public static string SuctionGripper {
            get {
                return ResourceManager.GetString("SuctionGripper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Mode.
        /// </summary>
        public static string SuctionGripper_ControlMode {
            get {
                return ResourceManager.GetString("SuctionGripper_ControlMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The control mode for the suction gripper..
        /// </summary>
        public static string SuctionGripper_ControlMode_Description {
            get {
                return ResourceManager.GetString("SuctionGripper_ControlMode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grip Mode.
        /// </summary>
        public static string SuctionGripper_GripMode {
            get {
                return ResourceManager.GetString("SuctionGripper_GripMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method through which visuals should be gripped by the suction gripper..
        /// </summary>
        public static string SuctionGripper_GripMode_Description {
            get {
                return ResourceManager.GetString("SuctionGripper_GripMode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gripped Visuals.
        /// </summary>
        public static string SuctionGripper_GrippedVisuals {
            get {
                return ResourceManager.GetString("SuctionGripper_GrippedVisuals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The visuals currently gripped by the suction gripper..
        /// </summary>
        public static string SuctionGripper_GrippedVisuals_Description {
            get {
                return ResourceManager.GetString("SuctionGripper_GrippedVisuals_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mass Limit.
        /// </summary>
        public static string SuctionGripper_MassLimit {
            get {
                return ResourceManager.GetString("SuctionGripper_MassLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum mass that the suction gripper is able to grip..
        /// </summary>
        public static string SuctionGripper_MassLimit_Description {
            get {
                return ResourceManager.GetString("SuctionGripper_MassLimit_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mass Limit Enabled.
        /// </summary>
        public static string SuctionGripper_MassLimitEnabled {
            get {
                return ResourceManager.GetString("SuctionGripper_MassLimitEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether to limit the mass of loads that can be gripped by the suction gripper..
        /// </summary>
        public static string SuctionGripper_MassLimitEnabled_Description {
            get {
                return ResourceManager.GetString("SuctionGripper_MassLimitEnabled_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string SuctionGripper_State {
            get {
                return ResourceManager.GetString("SuctionGripper_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether suction is currently enabled on the suction gripper..
        /// </summary>
        public static string SuctionGripper_State_Description {
            get {
                return ResourceManager.GetString("SuctionGripper_State_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer Load Source.
        /// </summary>
        public static string TimerLoadSource {
            get {
                return ResourceManager.GetString("TimerLoadSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Interval.
        /// </summary>
        public static string TimerLoadSource_InitialInterval {
            get {
                return ResourceManager.GetString("TimerLoadSource_InitialInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The time before the first load is released..
        /// </summary>
        public static string TimerLoadSource_InitialInterval_Description {
            get {
                return ResourceManager.GetString("TimerLoadSource_InitialInterval_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Interval.
        /// </summary>
        public static string TimerLoadSource_ReleaseInterval {
            get {
                return ResourceManager.GetString("TimerLoadSource_ReleaseInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum time between each load being released..
        /// </summary>
        public static string TimerLoadSource_ReleaseInterval_Description {
            get {
                return ResourceManager.GetString("TimerLoadSource_ReleaseInterval_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] UnknownAspect {
            get {
                object obj = ResourceManager.GetObject("UnknownAspect", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualization.
        /// </summary>
        public static string Visualization_Category {
            get {
                return ResourceManager.GetString("Visualization_Category", resourceCulture);
            }
        }
    }
}
